### ISSUE TITLE
Help with adjacent tagged variant

### ISSUE THREAD

**Issue by cosenmarco** [dtolnay/serde-yaml#124]
Given the following code: 
```rust
[...]
    let model_file_content = fs::read_to_string(model_file)
        .expect("Something went wrong reading the file");

    debug!("YAML content is: {:?}", model_file_content);

    let deserialized_model_def: ModelDef = serde_yaml::from_str(&model_file_content).unwrap();
    debug!("{:?}", deserialized_model_def);
[...]


#[derive(Deserialize, Debug)]
pub struct ModelDef {
    pub blocks: Vec<ModelDefBlock>,
    pub connections: Vec<ModelDefConnection>
}

#[derive(Deserialize, Debug)]
pub struct ModelDefConnection {
    pub from: ModelDefConnectionPort,
    pub to: Vec<ModelDefConnectionPort>
}

#[derive(Deserialize, Debug)]
pub struct ModelDefConnectionPort {
    pub block: String,
    pub port: String
}

#[derive(Deserialize, Debug)]
pub struct ModelDefBlock {
    pub id: String,
    pub implementation: String,
    #[serde(flatten)]
    pub configuration: ModelDefBlockConfig
}

#[derive(Deserialize, Debug)]
#[serde(tag = "implementation", content = "configuration")]
pub enum ModelDefBlockConfig {
    EventGenerator(ModelDefEventGeneratorConfiguration),
    LoggingSink
}

#[derive(Deserialize, Debug)]
pub struct ModelDefEventGeneratorConfiguration {
    pub event_type: String,
    pub frequency: f64
}
```

When I run it with the following YAML:

```yaml
---
  # TODO: imports
  blocks:
    - id: gen_001
      implementation: EventGenerator
      configuration:
        event_type: TriggerEvent
        frequency: 3
    - id: sink_001
      implementation: LoggingSink
    - id: sink_002
      implementation: LoggingSink
    
  connections:
    - from:
        block: gen_001
        port: out
      to:
        - block: sink_001
          port: in
        - block: sink_002
          port: in
```

I get the following output
```
2019-01-05 12:04:55 INFO  [softeelab] Model file is resources/testmodel.yml
2019-01-05 12:04:55 DEBUG [softeelab] YAML content is: "---\n  # TODO: imports\n  blocks:\n    - id: gen_001\n      implementation: EventGenerator\n      configuration:\n        event_type: TriggerEvent\n        frequency: 3\n    - id: sink_001\n      implementation: LoggingSink\n    - id: sink_002\n      implementation: LoggingSink\n    \n  connections:\n    - from:\n        block: gen_001\n        port: out\n      to:\n        - block: sink_001\n          port: in\n        - block: sink_002\n          port: in\n        "
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("missing field `implementation`", Some(Pos { marker: Marker { index: 40, line: 4, col: 8 }, path: "blocks[0]" }))', libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: <std::collections::hash::map::RandomState as core::default::Default>::default
             at libcore/macros.rs:26
   9: <std::collections::hash::map::RandomState as core::default::Default>::default
             at libcore/result.rs:808
  10: std::sys_common::poison::Flag::borrow
             at src/lib.rs:24
  11: softeelab::main
             at src/main.rs:25
  12: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  13: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  14: macho_symbol_search
             at libpanic_unwind/lib.rs:102
  15: std::alloc::default_alloc_error_hook
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  16: std::rt::lang_start
             at libstd/rt.rs:74
  17: softeelab::main
```
Which is confusing because the `implementation` field is there. What am I doing wrong?
I can share more of the surrounding code if necessary.

My Cargo.toml dependencies:
```
[dependencies]
log = "0.4.6"
simple_logger = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml="0.8"
yaml-rust = "0.4.2"
clap = "2.32.0"
```

**Comment by cosenmarco** [comment]
It's working, thanks.
I think though this it's worth mentioning in the documentation using less minimalistic example in https://serde.rs/enum-representations.html
or maybe I missed where this is mentioned...
