### ISSUE TITLE
Panic: attempted to leave type `linked_hash_map::Node<value::Value, value::Value>` uninitialized, which is invalid

### ISSUE THREAD

**Issue by sbstp** [dtolnay/serde-yaml#182]
Hello, I use serde_yaml in one of my projects and I've just ran into a panic which I've never had before. The only thing that has changed since my previous builds is the rustc version which is now 1.48.0. I'm running on Ubuntu 18.04.

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<value::Value, value::Value>` uninitialized, which is invalid', /home/simon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
```

The project is open source, you can take a look at the code here:
* https://github.com/sbstp/kubie/blob/master/src/kubeconfig.rs#L214
* https://github.com/sbstp/kubie/blob/master/src/ioutil.rs#L34

I would expect to get an error instead of a panic if my YAML is not valid.

Full backtrace:

```
thread 'main' panicked at 'attempted to leave type `linked_hash_map::Node<value::Value, value::Value>` uninitialized, which is invalid', /home/simon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::mem::uninitialized
             at /home/simon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:658
   4: linked_hash_map::LinkedHashMap<K,V,S>::ensure_guard_node
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:174
   5: linked_hash_map::LinkedHashMap<K,V,S>::insert
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/linked-hash-map-0.5.2/src/lib.rs:304
   6: serde_yaml::mapping::Mapping::insert
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/mapping.rs:53
   7: <serde_yaml::value::de::<impl serde::de::Deserialize for serde_yaml::value::Value>::deserialize::ValueVisitor as serde::de::Visitor>::visit_map
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/value/de.rs:107
   8: serde_yaml::de::Deserializer::visit_mapping::{{closure}}
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:175
   9: serde_yaml::de::Deserializer::recursion_check
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:239
  10: serde_yaml::de::Deserializer::visit_mapping
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:169
  11: <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_any
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:657
  12: serde_yaml::value::de::<impl serde::de::Deserialize for serde_yaml::value::Value>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/value/de.rs:114
  13: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:786
  14: <serde_yaml::de::MapAccess as serde::de::MapAccess>::next_value_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:365
  15: serde::de::MapAccess::next_value
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1847
  16: <&mut A as serde::de::MapAccess>::next_value
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1928
  17: <kubie::kubeconfig::_IMPL_DESERIALIZE_FOR_NamedCluster::<impl serde::de::Deserialize for kubie::kubeconfig::NamedCluster>::deserialize::__Visitor as serde::de::Visitor>::visit_map
             at ./src/kubeconfig.rs:27
  18: serde_yaml::de::Deserializer::visit_mapping::{{closure}}
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:175
  19: serde_yaml::de::Deserializer::recursion_check
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:239
  20: serde_yaml::de::Deserializer::visit_mapping
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:169
  21: <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_struct
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:923
  22: kubie::kubeconfig::_IMPL_DESERIALIZE_FOR_NamedCluster::<impl serde::de::Deserialize for kubie::kubeconfig::NamedCluster>::deserialize
             at ./src/kubeconfig.rs:27
  23: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:786
  24: <serde_yaml::de::SeqAccess as serde::de::SeqAccess>::next_element_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:311
  25: serde::de::SeqAccess::next_element
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1708
  26: <&mut A as serde::de::SeqAccess>::next_element
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1737
  27: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/impls.rs:866
  28: serde_yaml::de::Deserializer::visit_sequence::{{closure}}
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:158
  29: serde_yaml::de::Deserializer::recursion_check
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:239
  30: serde_yaml::de::Deserializer::visit_sequence
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:156
  31: <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_seq
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:870
  32: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/impls.rs:877
  33: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:786
  34: <serde_yaml::de::MapAccess as serde::de::MapAccess>::next_value_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:365
  35: serde::de::MapAccess::next_value
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1847
  36: <&mut A as serde::de::MapAccess>::next_value
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:1928
  37: <kubie::kubeconfig::_IMPL_DESERIALIZE_FOR_KubeConfig::<impl serde::de::Deserialize for kubie::kubeconfig::KubeConfig>::deserialize::__Visitor as serde::de::Visitor>::visit_map
             at ./src/kubeconfig.rs:16
  38: serde_yaml::de::Deserializer::visit_mapping::{{closure}}
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:175
  39: serde_yaml::de::Deserializer::recursion_check
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:239
  40: serde_yaml::de::Deserializer::visit_mapping
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:169
  41: <&mut serde_yaml::de::Deserializer as serde::de::Deserializer>::deserialize_map
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:902
  42: kubie::kubeconfig::_IMPL_DESERIALIZE_FOR_KubeConfig::<impl serde::de::Deserialize for kubie::kubeconfig::KubeConfig>::deserialize
             at ./src/kubeconfig.rs:16
  43: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:786
  44: serde_yaml::de::from_str_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:1042
  45: serde_yaml::de::from_slice_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:1127
  46: serde_yaml::de::from_reader_seed
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:1090
  47: serde_yaml::de::from_reader
             at /home/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_yaml-0.8.11/src/de.rs:1071
  48: kubie::ioutil::read_yaml
             at ./src/ioutil.rs:41
  49: kubie::kubeconfig::load_kubeconfigs
             at ./src/kubeconfig.rs:217
  50: kubie::kubeconfig::get_installed_contexts
             at ./src/kubeconfig.rs:242
  51: kubie::cmd::context::context
             at ./src/cmd/context.rs:64
  52: kubie::main
             at ./src/main.rs:29
  53: core::ops::function::FnOnce::call_once
             at /home/simon/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sbstp** [comment]
I did a `cargo update` and rebuilt, the panic is gone.
```
    Updating crates.io index
      Adding addr2line v0.14.0
      Adding adler v0.2.3
    Removing adler32 v1.0.4
    Updating anyhow v1.0.26 -> v1.0.34
    Removing arc-swap v0.4.4
    Updating arrayref v0.3.5 -> v0.3.6
    Updating arrayvec v0.5.1 -> v0.5.2
      Adding autocfg v1.0.1
    Updating backtrace v0.3.40 -> v0.3.55
    Removing backtrace-sys v0.1.32
      Adding base64 v0.13.0
    Updating blake2b_simd v0.5.10 -> v0.5.11
    Updating bumpalo v3.2.1 -> v3.4.0
    Updating byteorder v1.3.2 -> v1.3.4
    Updating bytes v0.5.4 -> v0.5.6
    Updating cc v1.0.49 -> v1.0.65
      Adding cfg-if v1.0.0
    Updating clap v2.33.0 -> v2.33.3
    Removing cloudabi v0.0.3
    Updating constant_time_eq v0.1.4 -> v0.1.5
    Updating crc32fast v1.2.0 -> v1.2.1
    Updating crossbeam-utils v0.6.6 -> v0.8.1
    Updating dirs-sys v0.3.4 -> v0.3.5
    Updating dtoa v0.4.4 -> v0.4.6
    Updating failure v0.1.6 -> v0.1.8
    Removing failure_derive v0.1.6
    Updating flate2 v1.0.13 -> v1.0.19
    Updating fnv v1.0.6 -> v1.0.7
      Adding form_urlencoded v1.0.0
    Removing fuchsia-cprng v0.1.1
    Updating getrandom v0.1.14 -> v0.1.15
      Adding gimli v0.23.0
    Updating hermit-abi v0.1.6 -> v0.1.17
    Updating http v0.2.0 -> v0.2.1
    Updating itoa v0.4.5 -> v0.4.6
    Updating js-sys v0.3.37 -> v0.3.46
    Updating libc v0.2.66 -> v0.2.80
    Updating linked-hash-map v0.5.2 -> v0.5.3
    Updating log v0.4.8 -> v0.4.11
    Updating miniz_oxide v0.3.6 -> v0.4.3
      Adding object v0.22.0
      Adding once_cell v1.5.2
    Updating os_info v2.0.2 -> v2.0.8
    Updating ppv-lite86 v0.2.6 -> v0.2.10
    Updating proc-macro-error v0.4.4 -> v1.0.4
    Updating proc-macro-error-attr v0.4.3 -> v1.0.4
    Updating proc-macro2 v1.0.7 -> v1.0.24
    Updating quote v1.0.2 -> v1.0.7
    Removing rand_core v0.3.1
    Removing rand_core v0.4.2
    Removing rand_os v0.1.3
    Removing rdrand v0.4.0
    Updating redox_syscall v0.1.56 -> v0.1.57
    Updating redox_users v0.3.1 -> v0.3.5
    Updating remove_dir_all v0.5.2 -> v0.5.3
    Updating ring v0.16.12 -> v0.16.18
    Updating rust-argon2 v0.5.1 -> v0.8.3
    Updating rustc-demangle v0.1.16 -> v0.1.18
    Removing rustversion v1.0.1
    Updating ryu v1.0.2 -> v1.0.5
    Updating serde v1.0.104 -> v1.0.117
    Updating serde_derive v1.0.104 -> v1.0.117
    Updating serde_json v1.0.48 -> v1.0.59
    Updating serde_yaml v0.8.11 -> v0.8.14
    Updating signal-hook v0.1.13 -> v0.1.16
    Updating signal-hook-registry v1.2.0 -> v1.2.2
    Removing smallvec v1.2.0
    Updating structopt v0.3.7 -> v0.3.21
    Updating structopt-derive v0.4.0 -> v0.4.14
    Updating syn v1.0.13 -> v1.0.53
    Removing syn-mid v0.4.0
    Removing synstructure v0.12.3
      Adding tinyvec v1.1.0
      Adding tinyvec_macros v0.1.0
    Updating unicode-normalization v0.1.12 -> v0.1.16
    Updating unicode-segmentation v1.6.0 -> v1.7.1
    Updating unicode-width v0.1.7 -> v0.1.8
    Updating unicode-xid v0.2.0 -> v0.2.1
    Updating untrusted v0.7.0 -> v0.7.1
    Updating url v2.1.1 -> v2.2.0
    Updating vec_map v0.8.1 -> v0.8.2
      Adding version_check v0.9.2
    Updating wasm-bindgen v0.2.60 -> v0.2.69
    Updating wasm-bindgen-backend v0.2.60 -> v0.2.69
    Updating wasm-bindgen-macro v0.2.60 -> v0.2.69
    Updating wasm-bindgen-macro-support v0.2.60 -> v0.2.69
    Updating wasm-bindgen-shared v0.2.60 -> v0.2.69
    Updating web-sys v0.3.37 -> v0.3.46
    Updating webpki v0.21.2 -> v0.21.3
    Updating which v3.1.0 -> v3.1.1
    Updating wildmatch v1.0.3 -> v1.0.12
    Updating winapi v0.3.8 -> v0.3.9
    Updating yaml-rust v0.4.3 -> v0.4.4
```

**Comment by sbstp** [comment]
I will close this since it seems to be fixed by newer versions.

**Comment by dtolnay** [comment]
Yeah this was a bug in old versions of the linked-hash-map crate.
